name: CI
description: Continuous Integration Workflow

on:                    #when to trigger
  push:                
    branches:           # List of branches
      - features/*
jobs:
  build:    # job name  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: 
          flutter-version: '3.38.9'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk

